### ISSUE TITLE
Templates: Update Entertainment templates to 9:16

### ISSUE THREAD

**Issue by mariano-formidable** [GoogleForCreators/web-stories-wp#2474]
Use this Figma doc to apply 9:16 updates to the existing `Entertainment` template:
https://www.figma.com/file/RTzSw47oi6pEZXEfP2JoBo/Templates?node-id=766%3A61

**Comment by csossi** [comment]
Tested in QA - PR#2603

Should be 3 "Out Now"s:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/480c6834-cb79-4ea8-9961-f59d12b18e80)
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/1941886d-06cf-44b9-97ff-70dbd3ebef74)

Social buttons still appearing:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/88acfc16-b8bd-4f5c-9d92-c82b73cca47d)

**Comment by mariano-formidable** [comment]
I fixed the issues you found and applied the updates to: #2603 

I fixed the highlighting so all 3 "Out Nows" are visible:
![image](https://user-images.githubusercontent.com/40646372/85755583-edef1200-b6c2-11ea-896b-02ad707b49c5.png)

The last page should not have social icons and should be formatted as shown in the figma doc:
![image](https://user-images.githubusercontent.com/40646372/85755703-06f7c300-b6c3-11ea-84c0-525fadf3dcfb.png)

**Comment by csossi** [comment]
Sorry, @mariano-formidable  - must've missed this broken image:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/d6837b1f-9bb5-4a16-a76a-ecc712d3b58f)

**Comment by mariano-formidable** [comment]
Hmmm... I'm not sure why the image didn't show up, but I went ahead and re-uploaded the image and re-updated the template json so hopefully this fixes the issue:
![image](https://user-images.githubusercontent.com/40646372/85889843-18170180-b7a1-11ea-8b33-03b0a8be2de7.png)

If this image or another fails to load can you open up the network panel of your browser and paste in the full url for the missing image?  I'm curious if the urls are being malformed for some reason.

**Comment by swissspidy** [comment]
We've had some network issues on Pantheon, so also try hard-refreshing the browser a couple of times

**Comment by csossi** [comment]
tried multiple hard refreshes too - still seeing a broken image here. From devtools:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/97ad696d-dab1-4ea8-a7b9-08cbce1e7ab2)

<img draggable="false" src="https://google.github.io/web-stories-wp/plugin-assets/images/templates/entertainment/ent_page8_image3.jpg" alt="ent_page8_image3" width="248.10874" height="98.67961250000002" scale="110" class="display__Img-r5mvch-0 bWhbaS">

**Comment by swissspidy** [comment]
Same thing as https://github.com/google/web-stories-wp/issues/2472#issuecomment-650440917 then.

If the template is otherwise displayed fine & works locally, let's move to QA-passed

**Comment by mariano-formidable** [comment]
I'm agreeing with Pascal on this one.  I'm going to merge and will double check staging to make sure the template loads properly.
